<a href="https://colab.research.google.com/github/Berkay86/DeepPerson/blob/main/Design.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
n=int(input("Değer giriniz"))
gozlemler = np.zeros((n, n))
for i in range(n):
  for j in range(n):
        gozlemler[i][j] = float(input("Lütfen [{}, {}] indeksindeki değeri girin: ".format(i, j)))




Değer giriniz5
Lütfen [0, 0] indeksindeki değeri girin: 7
Lütfen [0, 1] indeksindeki değeri girin: 7
Lütfen [0, 2] indeksindeki değeri girin: 15
Lütfen [0, 3] indeksindeki değeri girin: 11
Lütfen [0, 4] indeksindeki değeri girin: 9
Lütfen [1, 0] indeksindeki değeri girin: 12
Lütfen [1, 1] indeksindeki değeri girin: 17
Lütfen [1, 2] indeksindeki değeri girin: 12
Lütfen [1, 3] indeksindeki değeri girin: 18
Lütfen [1, 4] indeksindeki değeri girin: 18
Lütfen [2, 0] indeksindeki değeri girin: 14
Lütfen [2, 1] indeksindeki değeri girin: 18
Lütfen [2, 2] indeksindeki değeri girin: 18
Lütfen [2, 3] indeksindeki değeri girin: 19
Lütfen [2, 4] indeksindeki değeri girin: 19
Lütfen [3, 0] indeksindeki değeri girin: 19
Lütfen [3, 1] indeksindeki değeri girin: 25
Lütfen [3, 2] indeksindeki değeri girin: 22
Lütfen [3, 3] indeksindeki değeri girin: 19
Lütfen [3, 4] indeksindeki değeri girin: 23
Lütfen [4, 0] indeksindeki değeri girin: 7
Lütfen [4, 1] indeksindeki değeri girin: 10
Lütfen [4, 2] indeksi

In [20]:
gozlemler

array([[ 7.,  7., 15., 11.,  9.],
       [12., 17., 12., 18., 18.],
       [14., 18., 18., 19., 19.],
       [19., 25., 22., 19., 23.],
       [ 7., 10., 11., 15., 11.]])

In [33]:
satir_toplamlari = np.sum(gozlemler, axis=1)
satir_ortalamalari = np.mean(gozlemler, axis=1)
satir_toplamlarinın_toplami = np.sum(np.sum(gozlemler, axis=0))
satir_ortalamalari_ortalamasi = np.mean(satir_ortalamalari, axis=0)
print(satir_toplamlari)
print(satir_ortalamalari)
print(satir_toplamlarinın_toplami )
print(satir_ortalamalari_ortalamasi )


[ 49.  77.  88. 108.  54.]
[ 9.8 15.4 17.6 21.6 10.8]
376.0
15.040000000000001


In [ ]:
satir_toplamlari = np.sum(gozlemler, axis=1)
satir_ortalamalari = np.mean(gozlemler, axis=1)
satir_toplamlarinın_toplami = np.sum(np.sum(gozlemler, axis=0))
satir_ortalamalari_ortalamasi = np.mean(satir_ortalamalari, axis=0)
print(satir_toplamlari)
print(satir_ortalamalari)
print(satir_toplamlarinın_toplami )
print(satir_ortalamalari_ortalamasi )


[ 49.  77.  88. 108.  54.]
[ 9.8 15.4 17.6 21.6 10.8]
376.0
15.040000000000001


In [63]:
import scipy.stats as stats
SST=np.sum(np.square(gozlemler))-(satir_toplamlarinın_toplami**2)/(n**2)
SSB=np.sum(np.square(satir_toplamlari)/n)-(satir_toplamlarinın_toplami**2)/(n**2)
SSW=SST-SSB
dfb=n-1
dfw=n**2-n
dftotal=n**2-1
MSB=SSB/dfb
MSW=SSW/dfw
F=MSB/MSW
print(SST)
print(SSB)
print(SSW)
print(dfb)
print(dfw)
print(dftotal)
print(MSB)
print(MSW)
print(F)
f_value = stats.f.ppf(q=1-0.05, dfn=dfb, dfd=dfw)
print(f_value)

636.96
475.7600000000002
161.19999999999982
4
20
24
118.94000000000005
8.059999999999992
14.756823821339973
2.8660814020156584


In [56]:
import scipy.stats as stats

# İki grup arasındaki varyansların karşılaştırılması
f_value, p_value = stats.f_oneway(group1, group2)


1


5